### ISSUE TITLE
stack trace while using frequency range scanning in branch master

### ISSUE THREAD

**Issue by Marzona** [Marzona/rig-remote#20]
Got running rig-remote. All parts ok except when entered Min 1000 Max 2000 Interval 25
I get error in console:
Exception in Tkinter callback
Traceback (most recent call last):
File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in call
return self.func(args)
File "/home/zilvis/src/rig-remote/modules/ui.py", line 574, in frequency_start
self.scan("frequency", "start")
File "/home/zilvis/src/rig-remote/modules/ui.py", line 622, in scan
task = scanning.scan(scanning_task)
File "/home/zilvis/src/rig-remote/modules/scanning.py", line 137, in scan
updated_task = self._frequency(task, rigctl)
File "/home/zilvis/src/rig-remote/modules/scanning.py", line 149, in _frequency
for i in range(task.monitoring_loops):
Exception in Tkinter callback
Traceback (most recent call last):
File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call
return self.func(args)
File "/home/zilvis/src/rig-remote/modules/ui.py", line 574, in frequency_start
self._scan("frequency", "start")
File "/home/zilvis/src/rig-remote/modules/ui.py", line 622, in _scan
task = scanning.scan(scanning_task)
File "/home/zilvis/src/rig-remote/modules/scanning.py", line 137, in scan
updated_task = self._frequency(task, rigctl)
File "/home/zilvis/src/rig-remote/modules/scanning.py", line 149, in _frequency
for i in range(task.monitoring_loops):
TypeError: range() integer end argument expected, got str.

Can't figure out what could be wrong (locale? wrong python version)

**Comment by MaineTim** [comment]
Just curious... I'm not at a machine that is running rig-remote right now... is this error still occuring in the devel branch? 

EDIT: Okay, now I've had a chance to test it here, and I can't duplicate it in either the master or devel branch.

**Comment by Marzona** [comment]
hey Tim,

sorry I wasn't able to reply to you on this.

closing this issue as resolved in devel
