### ISSUE TITLE
bookmark scanning still does not work after update from Devel..??

### ISSUE THREAD

**Issue by dinofirstianto** [Marzona/rig-remote#21]
**If there is something wrong with my code ?** 
**This is my first experience using github and i use the master branch - >** https://github.com/Marzona/rig-remote.git 

Traceback (most recent call last):
  File "/Users/andinofirstianto/rig-remote/modules/scanning.py", line 121, in **init**
    self.range_min = khertz_to_hertz(int(range_min.replace(',', '')))
ValueError: invalid literal for int() with base 10: ''
03/13/2016 06:27:05 PM UTC range_max:
Traceback (most recent call last):
  File "/Users/andinofirstianto/rig-remote/modules/scanning.py", line 121, in **init**
    self.range_min = khertz_to_hertz(int(range_min.replace(',', '')))
ValueError: invalid literal for int() with base 10: ''
03/13/2016 06:27:05 PM UTC range_min:
Traceback (most recent call last):
  File "/Users/andinofirstianto/rig-remote/modules/scanning.py", line 121, in **init**
    self.range_min = khertz_to_hertz(int(range_min.replace(',', '')))
ValueError: invalid literal for int() with base 10: ''
03/13/2016 06:27:05 PM UTC interval:1
Traceback (most recent call last):
  File "/Users/andinofirstianto/rig-remote/modules/scanning.py", line 121, in **init**
    self.range_min = khertz_to_hertz(int(range_min.replace(',', '')))
ValueError: invalid literal for int() with base 10: ''
03/13/2016 06:27:05 PM UTC delay:1
Traceback (most recent call last):
  File "/Users/andinofirstianto/rig-remote/modules/scanning.py", line 121, in **init**
    self.range_min = khertz_to_hertz(int(range_min.replace(',', '')))
ValueError: invalid literal for int() with base 10: ''
03/13/2016 06:27:05 PM UTC passes:0
Traceback (most recent call last):
  File "/Users/andinofirstianto/rig-remote/modules/scanning.py", line 121, in **init**
    self.range_min = khertz_to_hertz(int(range_min.replace(',', '')))
ValueError: invalid literal for int() with base 10: ''
03/13/2016 06:27:05 PM UTC sgn_level:-25
Traceback (most recent call last):
  File "/Users/andinofirstianto/rig-remote/modules/scanning.py", line 121, in **init**
    self.range_min = khertz_to_hertz(int(range_min.replace(',', '')))
ValueError: invalid literal for int() with base 10: ''
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1536, in **call**
    return self.func(*args)
  File "/Users/andinofirstianto/rig-remote/modules/ui.py", line 885, in bookmark_toggle
    self._scan("bookmarks", action)
  File "/Users/andinofirstianto/rig-remote/modules/ui.py", line 991, in _scan
    wait)
  File "/Users/andinofirstianto/rig-remote/modules/scanning.py", line 121, in __init__
    self.range_min = khertz_to_hertz(int(range_min.replace(',', '')))
ValueError: invalid literal for int() with base 10: ''

**I try to check the devel brach status:** 
git checkout devel
Already on 'devel'
Your branch is up-to-date with 'origin/devel'.

It seems that i'm Ok...

**Comment by MaineTim** [comment]
Hi - Thanks for the report. Were the bookmarks created using the devel branch, or the master branch? Any chance you could post your bookmarks?

**Comment by MaineTim** [comment]
Hi - Thanks for the report. I was able to reproduce what I think is the problem by having one or more of the fields in "Scanning Options" or "Frequency Scanning" empty. Is that the case on your end? If so, an easy fix is just to delete the rig-remote config file (~/.rig-remote/rig-remote.conf) and the next run will fill in reasonable defaults. I'll fix the code to take care of the issue ASAP.

**Comment by MaineTim** [comment]
Pushed code to devel to handle blank parameter fields, and strip any non-numerics out before we process the field. Please let me know if that clears the problem for you. Thanks.

**Comment by MaineTim** [comment]
Devel branch has been updated with additional validation checks.
