### ISSUE TITLE
stack trace while issuing a bookmark scan

### ISSUE THREAD

**Issue by Marzona** [Marzona/rig-remote#29]
marzona@rubberduck:~/sdr/my-repo/rig-remote$ python ./rig-remote.py 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1539, in **call**
    return self.func(*args)
  File "/home/marzona/sdr/my-repo/rig-remote/modules/ui.py", line 1046, in bookmark_toggle
    self._scan("bookmarks", action)
  File "/home/marzona/sdr/my-repo/rig-remote/modules/ui.py", line 1206, in _scan
    nbl,
UnboundLocalError: local variable 'nbl' referenced before assignment

**Comment by Marzona** [comment]
fixed in devel in commit 8e92adc3fb01e6f2cdc37ab072c09db4b7f43ca4
